[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
universal_nft = "Ehu5ED6CaS9D4sF3Ltzvrs3EDD6AeWHjtLMfQxhKdZgm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/universal-nft"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.test.json -t 1000000 tests/**/*.ts"

[test]
upgradeable = true
