[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false


[programs.devnet]
universal_nft = "C2jwo1xMeUzb2Pb4xHU72yi4HrSzDdTZKXxtaJH6M5NX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 10000
shutdown_wait = 0

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
