[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false


[programs.devnet]
universal_nft = "3HMT1ceCh8QQjA8kGDDY13hVD8emCSrJY2aUNQYif9AY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
